#include <iostream>
using namespace std;

void Problem_1();
void Problem_2();
void Problem_3();
void Problem_4();
void Problem_5();
void Problem_6(); 
void Problem_7();
void Problem_8();
void Problem_9();
void Problem_10();
void Problem_11();
void Problem_12();
void Problem_13();
void Problem_14();
void Problem_15();
void Problem_16();
void Problem_17();
void Problem_18();
void Problem_19();
void Problem_20();
void Problem_21();
void Problem_22();
void Problem_23();
void Problem_24();
void Problem_25();
void Problem_26();
void Problem_27();
void Problem_28();
void Problem_29();
void Problem_30();
void Problem_31();
void Problem_32();
void Problem_33();
void Problem_34();
void Problem_35();
void Problem_36();
void Problem_37();
void Problem_38();
void Problem_39();
void Problem_40();
void Problem_41();


int main() {

    //Problem_1();
    //Problem_2();
    //Problem_3();
    //Problem_4();
    //Problem_5();
    //Problem_6();
    //Problem_7();
    //Problem_8();
    //Problem_9();
    //Problem_10();
    //Problem_11();
    //Problem_12();
    //Problem_13();
    //Problem_14();
    //Problem_15();
    //Problem_16();
    //Problem_17();
    //Problem_18();
    //Problem_19();
    //Problem_20();
    //Problem_21();
    //Problem_22();
    //Problem_23();
    //Problem_24();
    //Problem_25();
    //Problem_26();
    //Problem_27();
    //Problem_28();
    //Problem_29();
    //Problem_30();
    //Problem_31();
    //Problem_32();
    //Problem_33();
    //Problem_34();
    //Problem_35();
    //Problem_36();
    //Problem_37();
    //Problem_38();
    //Problem_39();
    //Problem_40();
    Problem_41();
}
